version: '3.9'
services: 
  db:
    image: postgres
    container_name: auth-api
    environment:  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./.localdb/data:/var/lib/postgresql/data
